### ISSUE TITLE
sounds like a skill issue ngl

### ISSUE THREAD

**Issue by itsmebombie** [kr8gz/malb8dge-rs#1]
the operator 
4#+{DSF+WF+WFSD{GF+ERG{ER+GEW{R#${@#$!@$R+WR@#$#@$+!
is not working bls help😭😭😭😭😭

**Comment by kr8gz** [comment]
have you tried deleting system32

**Comment by itsmebombie** [comment]
have you tried deleting /

**Comment by kr8gz** [comment]
have you tried getting some bitches

**Comment by itsmebombie** [comment]
no

**Comment by itsmebombie** [comment]
ok
